services:
  - type: web
    name: springboard-capstone
    env: node
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    rootDir: .
    autoDeploy: true

    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3000
